# Generated by Django 3.2.22 on 2023-12-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperformaces',
            name='fulfillment_rate',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalperformaces',
            name='on_time_delivery_rate',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='historicalperformaces',
            name='quality_rating_avg',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
