# Generated by Django 3.2.22 on 2023-12-11 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendor',
            new_name='Vendors',
        ),
    ]
