# Generated by Django 3.2.22 on 2023-12-12 10:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorders',
            name='po_number',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='vendor_code',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=32, unique=True),
        ),
    ]
