# Generated by Django 3.2.22 on 2023-12-12 10:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20231212_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorders',
            name='po_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='vendor_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
